name: deploy-orders

on:
  push:
    branches:
      - master
    paths:
      - "orders/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./orders
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t xu3g4pln/orders .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_TOKEN
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      - run: docker push xu3g4pln/orders
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ticketing
      - run: kubectl rollout restart deployment orders-deployment
